log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: transaction-indexing-svc
  service_port: 80

jwt_key:
  key: 32_character_jwtkey_for_token
  expiration:  "24h"

bitcoin:
  url: "url"
  user: "user"
  pass: "password"
  poll_interval: "5s"